apiVersion: v1
kind: Service
metadata:
  name: kube-verification-backend
  labels:
    io.kompose.service: kube-verification-backend
spec:
  type: NodePort
  ports:
  - name: "5002"
    port: 5002
    targetPort: 5002
    nodePort: 32002
  selector:
    io.kompose.service: kube-verification-backend