apiVersion: v1
kind: Service
metadata:
  name: kube-credential-backend
  labels:
    io.kompose.service: kube-credential-backend
spec:
  type: NodePort
  ports:
  - name: "5001"
    port: 5001
    targetPort: 5001
    nodePort: 32001
  selector:
    io.kompose.service: kube-credential-backend