apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-credential-backend
  labels:
    io.kompose.service: kube-credential-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kube-credential-backend
  template:
    metadata:
      labels:
        io.kompose.service: kube-credential-backend
    spec:
      containers:
      - name: kube-credential-backend
        image: project-kube-credential-backend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5001
        env:
        - name: DB_HOST
          value: host.docker.internal  
        - name: NODE_ENV
          value: production
      restartPolicy: Always